import { z } from "zod";
import {
  AddAdministratorMemberRequestSchema, AppendDocumentContractRequestSchema, BundleUploadQuerySchema,
  CreateDocumentTypeRequestSchema, CreateOperatorRequestSchema, CreateOperatorValidationRequestSchema,
  DocumentContractIdxSchema, DocumentTypeSchema, EtagSchema, IdSchema, ListAdminAuditEventsQuerySchema,
  ListBundlesQuerySchema, ListDocumentTypesQuerySchema, PaginationQuerySchema,
  UpdateCandidateMetadataRequestSchema, UpdateDocumentTypeRequestSchema,
} from "./schemas.js";

export const ADMIN_MCP_ZIP_MAX_BYTES = 8 * 1024 * 1024;
export const ADMIN_MCP_ZIP_MAX_BASE64_LENGTH = 4 * Math.ceil(ADMIN_MCP_ZIP_MAX_BYTES / 3);

export function isAdminMcpBase64Zip(value: string): boolean {
  if (value.length === 0 || value.length > ADMIN_MCP_ZIP_MAX_BASE64_LENGTH || value.length % 4 !== 0) return false;
  if (!/^[A-Za-z0-9+/]*={0,2}$/.test(value)) return false;
  const padding = value.endsWith("==") ? 2 : value.endsWith("=") ? 1 : 0;
  if (value.length / 4 * 3 - padding > ADMIN_MCP_ZIP_MAX_BYTES) return false;
  const last = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(value[value.length - padding - 1]!);
  return padding === 0 || (last & (padding === 2 ? 15 : 3)) === 0;
}

export const AdminMcpBase64ZipSchema = z.string().min(1).max(ADMIN_MCP_ZIP_MAX_BASE64_LENGTH)
  .refine(isAdminMcpBase64Zip, "Expected canonical standard base64 for a ZIP of at most 8 MiB")
  .describe("Standard padded base64 ZIP; no whitespace, data URL, or URL-safe alphabet.");
export const AdminMcpIdempotencyKeySchema = z.string().regex(/^[\x20-\x7e]{1,128}$/)
  .describe("Caller-provided logical retry identity, 1..128 printable ASCII characters. Never generated by the server.");

const mutation = { idempotencyKey: AdminMcpIdempotencyKeySchema };
const conditional = { ...mutation, etag: EtagSchema };
const confirmationEmail = z.string().refine(value => z.email().safeParse(value.trim().toLowerCase()).success)
  .describe("Explicit confirmation of the target administrator email.");
const upload = BundleUploadQuerySchema.unwrap().extend({ ...mutation, base64Zip: AdminMcpBase64ZipSchema }).strict();
const updateDocumentType = UpdateDocumentTypeRequestSchema.unwrap().safeExtend({
  documentType: DocumentTypeSchema,
  ...conditional,
  confirmEnabled: z.boolean().optional(),
  confirmOperatorId: IdSchema.optional(),
}).strict().superRefine((input, context) => {
  if (![input.internalName, input.typeCardBundleId, input.viewBundleId, input.builtinOperatorId, input.enabled].some(value => value !== undefined)) {
    context.addIssue({ code: "custom", message: "At least one document type setting must be updated" });
  }
  if (input.enabled !== undefined && input.confirmEnabled !== input.enabled) {
    context.addIssue({ code: "custom", path: ["confirmEnabled"], message: "Confirm the target enabled state" });
  }
  if (input.builtinOperatorId === null && input.confirmOperatorId === undefined) {
    context.addIssue({ code: "custom", path: ["confirmOperatorId"], message: "Confirm the current Operator identity" });
  }
  if ([input.typeCardBundleId, input.viewBundleId, input.builtinOperatorId].some(value => value !== undefined) && !input.reason?.trim()) {
    context.addIssue({ code: "custom", path: ["reason"], message: "Candidate selection requires a nonempty audit reason" });
  }
});

export const AdminMcpInputSchemas = {
  whoami: z.object({}).strict(),
  list_document_types: ListDocumentTypesQuerySchema.unwrap().strict(),
  get_document_type: z.object({ documentType: DocumentTypeSchema }).strict(),
  list_document_contracts: PaginationQuerySchema.unwrap().extend({ documentType: DocumentTypeSchema }).strict(),
  get_document_contract: z.object({ documentType: DocumentTypeSchema, documentContractIdx: DocumentContractIdxSchema }).strict(),
  list_type_card_bundles: ListBundlesQuerySchema.unwrap().strict(),
  get_type_card_bundle: z.object({ typeCardBundleId: IdSchema }).strict(),
  list_view_bundles: ListBundlesQuerySchema.unwrap().strict(),
  get_view_bundle: z.object({ viewBundleId: IdSchema }).strict(),
  get_operator_validation: z.object({ validationId: IdSchema }).strict(),
  list_operators: ListBundlesQuerySchema.unwrap().strict(),
  get_operator: z.object({ operatorId: IdSchema }).strict(),
  list_administrators: PaginationQuerySchema.unwrap().strict(),
  get_administrator: z.object({ adminId: IdSchema }).strict(),
  list_admin_audit_events: ListAdminAuditEventsQuerySchema.unwrap().strict(),
  append_document_contract: AppendDocumentContractRequestSchema.unwrap().extend({ documentType: DocumentTypeSchema, ...mutation }).strict(),
  upload_type_card_bundle: upload,
  update_type_card_bundle_metadata: UpdateCandidateMetadataRequestSchema.unwrap().extend({ typeCardBundleId: IdSchema, ...conditional }).strict(),
  upload_view_bundle: upload,
  update_view_bundle_metadata: UpdateCandidateMetadataRequestSchema.unwrap().extend({ viewBundleId: IdSchema, ...conditional }).strict(),
  create_operator_validation: CreateOperatorValidationRequestSchema.unwrap().extend(mutation).strict(),
  create_operator: CreateOperatorRequestSchema.unwrap().extend(mutation).strict(),
  update_operator_metadata: UpdateCandidateMetadataRequestSchema.unwrap().extend({ operatorId: IdSchema, ...conditional }).strict(),
  create_document_type: CreateDocumentTypeRequestSchema.unwrap().extend(mutation).strict(),
  update_document_type: updateDocumentType,
  add_administrator: AddAdministratorMemberRequestSchema.unwrap().extend({ ...mutation, confirmEmail: confirmationEmail }).strict()
    .refine(input => input.email.trim().toLowerCase() === input.confirmEmail.trim().toLowerCase(), { path: ["confirmEmail"], message: "Confirm the target email" }),
  remove_administrator: z.object({ adminId: IdSchema, ...conditional, confirmAdminId: IdSchema, confirmEmail: confirmationEmail }).strict()
    .refine(input => input.adminId === input.confirmAdminId, { path: ["confirmAdminId"], message: "Confirm the target administrator identity" }),
} as const;

export type AdminMcpToolInput<Name extends keyof typeof AdminMcpInputSchemas> = z.infer<typeof AdminMcpInputSchemas[Name]>;