packages:
  - 'packages/*'
  - 'unicas-packages/*'
overrides:
  '@jridgewell/sourcemap-codec': 1.5.5
allowBuilds:
  cpu-features: true
  esbuild: true
  protobufjs: true
  ssh2: true
  workerd: true
  sharp: true
  vue-demi: true
  core-js-pure: false
