import { useCallback, useEffect, useRef, useState } from "react";
import {
  Cable,
  Database,
  Gauge,
  LayoutDashboard,
  LogOut,
  Menu,
  ScrollText,
  ShieldCheck,
  Users,
  X,
} from "lucide-react";
import type { CasStack } from "@unicas/admin-client";
import { api } from "../api.js";
import { ConceptGuide, ErrorState, LoadingState, Page, Tabs } from "../components.js";
import { navigate } from "../router.js";
import { formatErrorSafe } from "./view-helpers.js";
import { StackOverviewView } from "./stack-overview.js";
import { MembersView } from "./members.js";
import { IssuerView } from "./issuer.js";
import { ControlAuditView } from "./control-audit.js";
import { RootRefAuditView, UsageView } from "./placeholder-views.js";

const TABS = [
  { id: "overview", label: "Overview", icon: <LayoutDashboard size={15} /> },
  { id: "members", label: "Members", icon: <Users size={15} /> },
  { id: "issuer", label: "OAuth issuer", icon: <ShieldCheck size={15} /> },
  { id: "audit", label: "Control audit", icon: <ScrollText size={15} /> },
  { id: "root-refs", label: "Root Ref audit", icon: <Database size={15} /> },
  { id: "usage", label: "Usage", icon: <Gauge size={15} /> },
] as const;

const TAB_GUIDES = {
  overview: {
    title: "Stack identity",
    summary: "A stack is UniCAS's top-level trust and data namespace. It isolates issuer trust, tenants, audit history, and stored CAS objects from every other stack.",
    concepts: [
      { term: "Stack ID", detail: "An immutable opaque identifier generated by UniCAS and used in native CAS routes." },
      { term: "Display name", detail: "A mutable operator-facing label. Changing it never changes the stack ID or stored data." },
      { term: "Revision", detail: "The version used for optimistic concurrency so stale admin updates cannot overwrite newer changes." },
    ],
  },
  members: {
    title: "Stack administrators",
    summary: "Members administer this stack through their OIDC identity. Tenant capabilities and admin sessions are separate authentication planes.",
    concepts: [
      { term: "Identity", detail: "Membership binds the provider issuer and immutable subject, not a changeable email address." },
      { term: "Equal access", detail: "All members currently have the same stack-administrator permissions." },
      { term: "Transfer", detail: "Invite the replacement first, then remove the previous member. UniCAS will not allow removal of the final member." },
    ],
  },
  issuer: {
    title: "Stack OAuth issuer",
    summary: "The stack trusts one OAuth authorization server whose issuer UniCAS discovered and proved control of. That server signs the short-lived capability tokens workloads use to call this stack's CAS data plane.",
    concepts: [
      { term: "Discovery", detail: "UniCAS fetches the issuer's RFC 8414/OIDC metadata and JWKS itself and validates compatibility — administrators never supply metadata, audiences, or keys." },
      { term: "Control proof", detail: "Activation requires signing UniCAS's challenge with a key the issuer currently advertises, so a stack cannot claim someone else's public issuer." },
      { term: "Key lifecycle", detail: "Verifiers refresh keys from the discovered JWKS URI after the authority cache TTL; providers publish overlapping keys for zero-downtime rotation." },
    ],
  },
  audit: {
    title: "Control-plane audit",
    summary: "This append-only log records administrative mutations to stack configuration and membership.",
    concepts: [
      { term: "Actor", detail: "The immutable OIDC identity that performed the operation." },
      { term: "Target", detail: "The stack resource changed by the operation, with a request ID when available." },
      { term: "Separate ledger", detail: "Control audit tracks administration. Root Ref audit tracks tenant data-plane reference changes." },
    ],
  },
  "root-refs": {
    title: "Root Ref audit",
    summary: "Root Ref events and domain balances explain which signed deltas CAS recorded. They support investigation and reconciliation, but do not prove business-system truth.",
    concepts: [
      { term: "Authoritative count", detail: "The aggregate node root count alone controls lifecycle and garbage collection." },
      { term: "Ref domain", detail: "A signed event field used to filter and aggregate changes by their responsible business system." },
      { term: "Reconciliation", detail: "Compare CAS history with business intent, then make an explicit repair decision outside this view." },
    ],
  },
  usage: {
    title: "Tenant storage usage",
    summary: "CAS accounting is isolated by stack and tenant. The admin session does not itself carry a tenant data-plane capability.",
    concepts: [
      { term: "Partition", detail: "Equal hashes in different stack-and-tenant partitions have independent objects, leases, references, and GC." },
      { term: "Permission", detail: "A usage read requires a tenant capability with cas:manage for the selected tenant." },
    ],
  },
} as const;

export function StackView({ stackId, onStackChange, onOpenMcpConfiguration, onLogout }: {
  stackId: string;
  onStackChange?: (stack: CasStack | null) => void;
  onOpenMcpConfiguration: () => void;
  onLogout: () => void;
}) {
  const [stack, setStack] = useState<CasStack | null>(null);
  const [stacks, setStacks] = useState<CasStack[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [tab, setTab] = useState<string>("overview");
  const [mobileNavigationOpen, setMobileNavigationOpen] = useState(false);
  const [reloadKey, setReloadKey] = useState(0);
  const navigationButtonRef = useRef<HTMLButtonElement>(null);
  const navigationCloseRef = useRef<HTMLButtonElement>(null);
  const navigationDrawerRef = useRef<HTMLElement>(null);

  const load = useCallback(async () => {
    setError(null);
    try {
      const [currentStack, stackList] = await Promise.all([
        api<CasStack>(`/admin/stacks/${encodeURIComponent(stackId)}`),
        api<{ items: CasStack[] }>("/admin/stacks"),
      ]);
      setStack(currentStack);
      setStacks(stackList.items);
      onStackChange?.(currentStack);
    } catch (caught) {
      setError(formatErrorSafe(caught));
    }
  }, [onStackChange, stackId]);

  useEffect(() => {
    void load();
  }, [load, reloadKey]);

  useEffect(() => {
    if (!mobileNavigationOpen) return;
    document.body.classList.add("drawer-open");
    const focusTimer = window.setTimeout(() => navigationCloseRef.current?.focus(), 200);
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        closeMobileNavigation();
        return;
      }
      if (event.key !== "Tab" || !navigationDrawerRef.current) return;
      const focusable = Array.from(navigationDrawerRef.current.querySelectorAll<HTMLElement>(
        "button:not([disabled]), select:not([disabled]), [href], [tabindex]:not([tabindex='-1'])",
      ));
      const first = focusable[0];
      const last = focusable[focusable.length - 1];
      if (!first || !last) return;
      if (event.shiftKey && document.activeElement === first) {
        event.preventDefault();
        last.focus();
      } else if (!event.shiftKey && document.activeElement === last) {
        event.preventDefault();
        first.focus();
      }
    };
    window.addEventListener("keydown", onKeyDown);
    return () => {
      window.clearTimeout(focusTimer);
      document.body.classList.remove("drawer-open");
      window.removeEventListener("keydown", onKeyDown);
    };
  }, [mobileNavigationOpen]);

  useEffect(() => {
    setMobileNavigationOpen(false);
  }, [stackId]);

  useEffect(() => {
    document.title = stack?.stackId === stackId ? `UniCAS | ${stack.displayName}` : "UniCAS";
    return () => {
      document.title = "UniCAS";
    };
  }, [stack, stackId]);

  useEffect(() => () => onStackChange?.(null), [onStackChange]);

  const reload = () => setReloadKey((key) => key + 1);
  const activeTab = TABS.find((item) => item.id === tab) ?? TABS[0];
  const activeGuide = TAB_GUIDES[activeTab.id];

  function closeMobileNavigation() {
    setMobileNavigationOpen(false);
    requestAnimationFrame(() => navigationButtonRef.current?.focus());
  }

  function selectTab(id: string) {
    setTab(id);
    if (mobileNavigationOpen) closeMobileNavigation();
  }

  if (error) return <Page title="Stack"><ErrorState message={error} /></Page>;
  if (!stack || !stacks) return <Page title="Stack"><LoadingState /></Page>;

  return (
    <Page title={stack.displayName}>
      <button
        ref={navigationButtonRef}
        type="button"
        className="mobile-nav-trigger"
        aria-controls="stack-navigation"
        aria-expanded={mobileNavigationOpen}
        aria-label={`Open navigation, current section ${activeTab.label}`}
        title={`Navigation: ${activeTab.label}`}
        onClick={() => setMobileNavigationOpen(true)}
      >
        <Menu size={19} />
      </button>
      <div className="stack-layout">
        {mobileNavigationOpen ? (
          <div
            className="drawer-overlay"
            aria-hidden="true"
            onClick={closeMobileNavigation}
          />
        ) : null}
        <aside
          ref={navigationDrawerRef}
          id="stack-navigation"
          className={`stack-sidebar${mobileNavigationOpen ? " stack-sidebar-open" : ""}`}
          role={mobileNavigationOpen ? "dialog" : undefined}
          aria-modal={mobileNavigationOpen ? true : undefined}
          aria-label="Stack management navigation"
        >
          <div className="drawer-header">
            <a className="drawer-brand" href="#/">
              <span className="brand-mark">U</span>
              <span>UniCAS Admin</span>
            </a>
            <button
              ref={navigationCloseRef}
              type="button"
              className="drawer-close"
              aria-label="Close navigation"
              onClick={closeMobileNavigation}
            >
              <X size={17} />
            </button>
          </div>
          <div className="stack-switcher">
            <label htmlFor="stack-switcher">Stack</label>
            <select
              id="stack-switcher"
              value={stackId}
              onChange={(event) => {
                navigate(`/stacks/${encodeURIComponent(event.target.value)}`);
                if (mobileNavigationOpen) closeMobileNavigation();
              }}
            >
              {stacks.map((option) => (
                <option key={option.stackId} value={option.stackId}>{option.displayName}</option>
              ))}
            </select>
          </div>
          <Tabs tabs={TABS} active={tab} onChange={selectTab} orientation="vertical" />
          <div className="drawer-footer">
            <button
              type="button"
              className="drawer-action"
              onClick={() => {
                closeMobileNavigation();
                onOpenMcpConfiguration();
              }}
            >
              <Cable size={15} />
              <span>Connect AI tools</span>
            </button>
            <button type="button" className="drawer-signout" onClick={onLogout}>
              <LogOut size={15} />
              <span>Sign out</span>
            </button>
          </div>
        </aside>
        <section className="stack-content" aria-hidden={mobileNavigationOpen ? true : undefined}>
          <ConceptGuide {...activeGuide} />
          {tab === "overview" ? <StackOverviewView stack={stack} onChanged={reload} /> : null}
          {tab === "members" ? <MembersView stackId={stackId} stackRevision={stack.revision} onChanged={reload} /> : null}
          {tab === "issuer" ? <IssuerView stackId={stackId} /> : null}
          {tab === "audit" ? <ControlAuditView stackId={stackId} /> : null}
          {tab === "root-refs" ? <RootRefAuditView stackId={stackId} /> : null}
          {tab === "usage" ? <UsageView stackId={stackId} /> : null}
        </section>
      </div>
    </Page>
  );
}
