/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.compute.jsonc --include-runtime=false --env-interface=ComputeEnv src/compute-env.d.ts` (hash: fc1f9f3f726e38477e32d05a1e3dc4fe)
interface __BaseEnv_ComputeEnv {
	COMPUTE_ORIGIN: "https://configure-compute-origin.invalid";
	PLATFORM_ID: "unidocs-platform";
	COMPUTE_ENVIRONMENT: "staging";
	COMPUTE_SERVICE_ID: "markdown-compute";
	CAS_ORIGIN: "https://configure-cas-origin.invalid";
	CAS_STACK_ID: "configure-isolated-stack";
	CAS_ISSUER: "https://configure-cas-issuer.invalid";
	CAS_AUDIENCE: "https://configure-cas-origin.invalid/stacks/configure-isolated-stack";
	CAS_JWKS_URL: "https://configure-cas-issuer.invalid/jwks";
	PLATFORM_NONCES: DurableObjectNamespace<import("./compute-worker").PlatformNonces>;
	CAS_SERVICE: Fetcher /* unidocs-cas */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./compute-worker");
		durableNamespaces: "PlatformNonces";
	}
	interface Env extends __BaseEnv_ComputeEnv {}
}
interface ComputeEnv extends __BaseEnv_ComputeEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "COMPUTE_ORIGIN" | "PLATFORM_ID" | "COMPUTE_ENVIRONMENT" | "COMPUTE_SERVICE_ID" | "CAS_ORIGIN" | "CAS_STACK_ID" | "CAS_ISSUER" | "CAS_AUDIENCE" | "CAS_JWKS_URL">> {}
}
