/**
 * Public entrypoint for UniDocs administrator control-plane contracts.
 */
export {
  DocumentContentFormatVersion,
  DocumentTypePattern,
  documentLocationContentType,
  documentSnapshotContentType,
} from "@unidocs/protocol";
export type { DocumentLocationContentType, DocumentSnapshotContentType } from "@unidocs/protocol";
export {
  AdminApiErrorMap,
  AdminApiV1BasePath,
  AdministratorMemberAuditActions,
  DocumentTypeAuditActions,
  adminApiContract,
} from "./contract.js";
export type {
  AdminApiContract,
  AdministratorMemberAuditAction,
  DocumentTypeAuditAction,
} from "./contract.js";
export {
  AddAdministratorMemberRequestSchema,
  AppendDocumentContractRequestSchema,
  AdminAuditActionSchema,
  AdminAuditEventSchema,
  AdminAuditResourceTypeSchema,
  AdminApiErrorSchema,
  AdministratorMemberMutationResultSchema,
  AdministratorMemberListItemSchema,
  AdministratorMemberRecordSchema,
  BundleUploadQuerySchema,
  ConditionalMutationHeadersSchema,
  CreateDocumentTypeRequestSchema,
  CreateOperatorCandidateRequestSchema,
  CreateOperatorValidationRequestSchema,
  DocumentContractIdxSchema,
  DocumentContractAppendResultSchema,
  DocumentContractListItemSchema,
  DocumentContractRecordSchema,
  DocumentTypeListItemSchema,
  DocumentTypeMutationResultSchema,
  DocumentTypeRegistrationSchema,
  DocumentTypeSchema,
  EtagSchema,
  ExternalEtagSchema,
  ListBundlesQuerySchema,
  ListAdminAuditEventsQuerySchema,
  ListAdminAuditEventsResponseSchema,
  ListAdministratorMembersResponseSchema,
  ListDocumentTypesQuerySchema,
  ListDocumentTypesResponseSchema,
  ListOperatorCandidatesResponseSchema,
  ListDocumentContractsResponseSchema,
  ListTypeCardBundlesResponseSchema,
  ListViewBundlesResponseSchema,
  MutationHeadersSchema,
  OperatorCandidateRecordSchema,
  OperatorCandidateListItemSchema,
  OperatorCandidateMutationResultSchema,
  OperatorDescriptorSchema,
  OperatorValidationSchema,
  PaginationQuerySchema,
  SValueSchemaSchema,
  TypeCardBundleManifestV1Schema,
  TypeCardBundleListItemSchema,
  TypeCardBundleMutationResultSchema,
  TypeCardBundleRecordSchema,
  TypeCardIconPngV1Schema,
  TypeCardIconSvgV1Schema,
  TypeCardIconV1Schema,
  TypeCardLocaleV1Schema,
  UpdateCandidateMetadataRequestSchema,
  UpdateDocumentTypeRequestSchema,
  ViewBundleManifestV1Schema,
  ViewBundleListItemSchema,
  ViewBundleMutationResultSchema,
  ViewBundleRecordSchema,
} from "./schemas.js";
export type {
  AddAdministratorMemberRequest,
  AppendDocumentContractRequest,
  AdminAuditAction,
  AdminAuditEvent,
  AdminApiError,
  AdministratorMemberMutationResult,
  AdministratorMemberListItem,
  AdministratorMemberRecord,
  CreateDocumentTypeRequest,
  CreateOperatorCandidateRequest,
  CreateOperatorValidationRequest,
  DocumentContractAppendResult,
  DocumentContractListItem,
  DocumentContractRecord,
  DocumentTypeListItem,
  DocumentTypeMutationResult,
  DocumentTypeRegistration,
  ListBundlesQuery,
  ListAdminAuditEventsQuery,
  ListAdminAuditEventsResponse,
  ListAdministratorMembersResponse,
  ListDocumentTypesQuery,
  ListDocumentTypesResponse,
  ListOperatorCandidatesResponse,
  ListDocumentContractsResponse,
  ListTypeCardBundlesResponse,
  ListViewBundlesResponse,
  OperatorCandidateRecord,
  OperatorCandidateListItem,
  OperatorCandidateMutationResult,
  OperatorDescriptor,
  OperatorValidation,
  TypeCardBundleManifestV1,
  TypeCardBundleListItem,
  TypeCardBundleMutationResult,
  TypeCardBundleRecord,
  TypeCardIconPngV1,
  TypeCardIconSvgV1,
  TypeCardIconV1,
  TypeCardLocaleV1,
  UpdateCandidateMetadataRequest,
  UpdateDocumentTypeRequest,
  ViewBundleManifestV1,
  ViewBundleListItem,
  ViewBundleMutationResult,
  ViewBundleRecord,
} from "./schemas.js";