/**
 * Public entrypoint for UniDocs administrator control-plane contracts.
 */
export {
  AdminApiErrorMap,
  AdminApiV1BasePath,
  AdministratorMemberAuditActions,
  DocumentTypeAuditActions,
  adminApiContract,
} from "./contract.js";
export type {
  AdminApiContract,
  AdministratorMemberAuditAction,
  DocumentTypeAuditAction,
} from "./contract.js";
export {
  AddAdministratorMemberRequestSchema,
  AdminApiErrorSchema,
  AdministratorMemberListItemSchema,
  AdministratorMemberRecordSchema,
  AppendSnapshotContractRequestSchema,
  BundleUploadQuerySchema,
  ConditionalMutationHeadersSchema,
  CreateDocumentTypeRequestSchema,
  CreateOperatorCandidateRequestSchema,
  CreateOperatorValidationRequestSchema,
  DocumentTypeRegistrationSchema,
  ListBundlesQuerySchema,
  ListAdministratorMembersResponseSchema,
  ListDocumentTypesQuerySchema,
  ListDocumentTypesResponseSchema,
  ListOperatorCandidatesResponseSchema,
  ListSnapshotContractsResponseSchema,
  ListTypeCardBundlesResponseSchema,
  ListViewBundlesResponseSchema,
  MutationHeadersSchema,
  OperatorCandidateRecordSchema,
  OperatorDescriptorSchema,
  OperatorValidationSchema,
  PaginationQuerySchema,
  SValueSchemaSchema,
  SnapshotContractRecordSchema,
  TypeCardBundleManifestV1Schema,
  TypeCardBundleRecordSchema,
  TypeCardIconPngV1Schema,
  TypeCardIconSvgV1Schema,
  TypeCardIconV1Schema,
  TypeCardLocaleV1Schema,
  UpdateCandidateMetadataRequestSchema,
  UpdateDocumentTypeRequestSchema,
  ViewBundleManifestV1Schema,
  ViewBundleRecordSchema,
} from "./schemas.js";
export type {
  AddAdministratorMemberRequest,
  AdminApiError,
  AdministratorMemberListItem,
  AdministratorMemberRecord,
  AppendSnapshotContractRequest,
  CreateDocumentTypeRequest,
  CreateOperatorCandidateRequest,
  CreateOperatorValidationRequest,
  DocumentTypeRegistration,
  ListBundlesQuery,
  ListAdministratorMembersResponse,
  ListDocumentTypesQuery,
  ListDocumentTypesResponse,
  ListOperatorCandidatesResponse,
  ListSnapshotContractsResponse,
  ListTypeCardBundlesResponse,
  ListViewBundlesResponse,
  OperatorCandidateRecord,
  OperatorDescriptor,
  OperatorValidation,
  SnapshotContractRecord,
  TypeCardBundleManifestV1,
  TypeCardBundleRecord,
  TypeCardIconPngV1,
  TypeCardIconSvgV1,
  TypeCardIconV1,
  TypeCardLocaleV1,
  UpdateCandidateMetadataRequest,
  UpdateDocumentTypeRequest,
  ViewBundleManifestV1,
  ViewBundleRecord,
} from "./schemas.js";