// GENERATED by scripts/build-ui-assets.mjs — do not edit.
// Stub: `vite build && node scripts/build-ui-assets.mjs && tsc` replaces this
// with the real built admin console assets for deployment.
export const UI_ASSETS: Record<string, string> = {};
