/** @deprecated Import control helpers from `@unicas/service`. */
export {
  canonicalJson,
  CAPABILITY_MAX_LIFETIME_SECONDS_MAX,
  CAPABILITY_MAX_LIFETIME_SECONDS_MIN,
  CONTROL_LIST_DEFAULT_LIMIT,
  CONTROL_LIST_MAX_LIMIT,
  DEFAULT_CAPABILITY_MAX_LIFETIME_SECONDS,
  INVITATION_TTL_MS,
  isSupportedKeyAlgorithm,
  KID_PATTERN,
  LEGACY_DOMAIN,
  normalizeEmailConstraint,
  parseControlListLimit,
  POSSESSION_CHALLENGE_TTL_MS,
  sha256Hex,
  STACK_ID_PATTERN,
  SUPPORTED_KEY_ALGORITHMS,
  validateAudience,
  validateCapabilityMaxLifetimeSeconds,
  validateDisplayName,
  validateEmailConstraint,
  validateInvitationToken,
  validateIssuer,
  validateKid,
} from "@unicas/service";
export type { SupportedKeyAlgorithm } from "@unicas/service";
