/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false src/env.generated.d.ts` (hash: 602ae90b7f1686e3a2e614a93af99890)
interface __BaseEnv_Env {
	DB: D1Database;
	PORTAL_ORIGIN: string;
	GATEWAY_OIDC_ISSUER: string;
	GATEWAY_OIDC_CLIENT_ID: string;
	PORTAL_BOOTSTRAP_EMAIL: string;
	GATEWAY_OIDC_CLIENT_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PORTAL_ORIGIN" | "GATEWAY_OIDC_ISSUER" | "GATEWAY_OIDC_CLIENT_ID" | "PORTAL_BOOTSTRAP_EMAIL" | "GATEWAY_OIDC_CLIENT_SECRET">> {}
}
