/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false src/env.generated.d.ts` (hash: 1dd9341252e464d722541c76f6a6e928)
interface __BaseEnv_Env {
	OAUTH_KV: KVNamespace;
	BUNDLES: R2Bucket;
	DB: D1Database;
	MCP_ENABLED: string;
	MCP_PUBLIC_ORIGIN: string;
	MCP_ADMIN_EMAIL_ALLOWLIST: string;
	MCP_CONTENT_MUTATIONS_ENABLED: string;
	MCP_PUBLISH_MUTATIONS_ENABLED: string;
	MCP_SECURITY_MUTATIONS_ENABLED: string;
	PORTAL_ORIGIN: string;
	BUNDLE_ORIGIN: string;
	GATEWAY_OIDC_ISSUER: string;
	GATEWAY_OIDC_CLIENT_ID: string;
	PORTAL_BOOTSTRAP_EMAIL: string;
	CAS_ORIGIN: string;
	CAS_STACK_ID: string;
	CAS_ISSUER: string;
	CAS_AUDIENCE: string;
	CAS_REF_DOMAIN: string;
	CAS_SIGNING_KID: string;
	PORTAL_TENANT_DEV_SESSION: string;
	GATEWAY_OIDC_CLIENT_SECRET: string;
	OAUTH_STATE_ENCRYPTION_KEY: string;
	MARKDOWN_OPERATOR_HMAC_KEY: string;
	CAS_SIGNING_KEY: string;
	AGENT_API_TOKEN: string;
	ADMIN_MARKDOWN_SERVICE: Fetcher /* unidocs-markdown */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MCP_ENABLED" | "MCP_PUBLIC_ORIGIN" | "MCP_ADMIN_EMAIL_ALLOWLIST" | "MCP_CONTENT_MUTATIONS_ENABLED" | "MCP_PUBLISH_MUTATIONS_ENABLED" | "MCP_SECURITY_MUTATIONS_ENABLED" | "PORTAL_ORIGIN" | "BUNDLE_ORIGIN" | "GATEWAY_OIDC_ISSUER" | "GATEWAY_OIDC_CLIENT_ID" | "PORTAL_BOOTSTRAP_EMAIL" | "CAS_ORIGIN" | "CAS_STACK_ID" | "CAS_ISSUER" | "CAS_AUDIENCE" | "CAS_REF_DOMAIN" | "CAS_SIGNING_KID" | "PORTAL_TENANT_DEV_SESSION" | "GATEWAY_OIDC_CLIENT_SECRET" | "OAUTH_STATE_ENCRYPTION_KEY" | "MARKDOWN_OPERATOR_HMAC_KEY" | "CAS_SIGNING_KEY" | "AGENT_API_TOKEN">> {}
}
