import { OpenAPIHandler } from "@orpc/openapi/fetch";
import { implement, ORPCError } from "@orpc/server";
import { experimental_ZodSmartCoercionPlugin } from "@orpc/zod/zod4";
import { adminApiContract } from "@unidocs/protocol-admin-portal";
import { OperatorOperationError, boundedBytes, createOperatorService, parseStrictJson, type AdminContext, type OperatorRepository } from "@unidocs/portal-service";

export function createOperatorsHttp(repository: OperatorRepository) {
  const implementation=implement(adminApiContract.operators).$context<{admin:AdminContext;requestId:string}>(); const service=createOperatorService(repository);
  const router={create:implementation.create.handler(({input,context})=>service.create(context.admin,input.body,input.headers["idempotency-key"],context.requestId)),list:implementation.list.handler(({input,context})=>service.list(context.admin,input.query)),get:implementation.get.handler(({input,context})=>service.get(context.admin,input.params.operatorId)),updateMetadata:implementation.updateMetadata.handler(({input,context})=>service.updateMetadata(context.admin,input.params.operatorId,input.body,input.headers["idempotency-key"],input.headers["if-match"],context.requestId))};
  return async(request:Request,admin:AdminContext,requestId:string)=>{const url=new URL(request.url);const collection=url.pathname==="/admin/api/v1/operators";const allowed=request.method==="GET"&&collection?["documentType","limit","cursor"]:[];const seen=new Set<string>();let invalid=false;url.searchParams.forEach((value,name)=>{if(seen.has(name)||!allowed.includes(name)||(name==="limit"&&!/^[1-9][0-9]*$/.test(value)))invalid=true;seen.add(name);});if(invalid)return Response.json({error:{code:"invalid_request",message:"The query is invalid",requestId}},{status:400});if(request.method==="PATCH"&&!request.headers.has("if-match"))return Response.json({error:{code:"precondition_required",message:"The If-Match precondition is required",requestId}},{status:428});
    let bounded=request;if(request.method==="POST"||request.method==="PATCH"){if(request.headers.get("content-type")?.split(";",1)[0].trim().toLowerCase()!=="application/json"||request.headers.has("content-encoding"))return Response.json({error:{code:"invalid_request",message:"A JSON request body is required",requestId}},{status:400});try{if(!request.body)throw new Error();const content=new Uint8Array(8192);let length=0;for await(const chunk of boundedBytes(request.body,content.length)){content.set(chunk,length);length+=chunk.byteLength;}parseStrictJson(content.subarray(0,length));bounded=new Request(request.url,{method:request.method,headers:request.headers,body:content.slice(0,length)});}catch{return Response.json({error:{code:"invalid_request",message:"Invalid or oversized JSON request",requestId}},{status:400});}}
    const handler=new OpenAPIHandler(router,{plugins:request.method==="GET"?[new experimental_ZodSmartCoercionPlugin()]:[],interceptors:[async({next})=>{try{return await next();}catch(error){if(error instanceof OperatorOperationError)throw new ORPCError(error.code.toUpperCase(),{status:{invalid_request:400,not_found:404,idempotency_conflict:409,precondition_failed:412,forbidden:403,operator_validation_required:409}[error.code],message:error.message,data:{requestId}});throw error;}}],customErrorResponseBodyEncoder:error=>({error:{code:error.status>=500?"internal_error":error.code==="BAD_REQUEST"?"invalid_request":error.code.toLowerCase(),message:error.status>=500?"Administrator operation failed":error.status===400?"The request is invalid":error.message,requestId}})});const result=await handler.handle(bounded,{context:{admin,requestId}});return result.matched?result.response:new Response(null,{status:404});};
}
