import type { D1Database, D1PreparedStatement } from "@cloudflare/workers-types";
import { OperatorListItemSchema, OperatorRecordSchema, OperatorValidationSchema, type ListBundlesQuery, type ListOperatorsResponse, type OperatorMutationResult, type OperatorRecord } from "@unidocs/protocol-admin-portal";
import { OperatorOperationError, schemaHash, type AdminContext, type OperatorCreateCommand, type OperatorMetadataCommand, type OperatorRepository } from "@unidocs/portal-service";

interface OperatorRow { operator_id: string; record_json: string; revision: number; created_at: number; }
export class D1OperatorRepository implements OperatorRepository {
  constructor(private readonly database: D1Database, private readonly now: () => number = () => Math.floor(Date.now() / 1000)) {}
  private authority(context: AdminContext): D1PreparedStatement { return this.database.prepare(`SELECT member_id FROM portal_administrators WHERE member_id=? AND issuer=? AND subject=? AND active=1 AND (?='bearer' OR EXISTS (SELECT 1 FROM portal_sessions s JOIN portal_session_families f ON s.family_id=f.family_id WHERE s.session_hash=? AND f.member_id=portal_administrators.member_id AND f.revoked_at IS NULL AND s.expires_at>?))`).bind(context.memberId, context.identity.issuer, context.identity.subject, context.transport, context.sessionHash ?? null, this.now()); }
  private guard(context: AdminContext): D1PreparedStatement { return this.database.prepare(`INSERT INTO portal_mutation_guard SELECT CASE WHEN EXISTS (SELECT 1 FROM portal_administrators WHERE member_id=? AND issuer=? AND subject=? AND active=1 AND (?='bearer' OR EXISTS (SELECT 1 FROM portal_sessions s JOIN portal_session_families f ON s.family_id=f.family_id WHERE s.session_hash=? AND f.member_id=portal_administrators.member_id AND f.revoked_at IS NULL AND s.expires_at>?))) THEN 1 ELSE 0 END`).bind(context.memberId, context.identity.issuer, context.identity.subject, context.transport, context.sessionHash ?? null, this.now()); }
  private async authorize(context: AdminContext) { if (!await this.authority(context).first()) throw new OperatorOperationError("forbidden"); }
  private async replay(context: AdminContext, operation: string, key: string, fingerprint: string): Promise<OperatorMutationResult | null> { await this.authorize(context); const row=await this.database.prepare("SELECT fingerprint,response_json FROM portal_idempotency_receipts WHERE actor_id=? AND operation=? AND key=?").bind(context.memberId,operation,key).first<{fingerprint:string;response_json:string}>(); if(!row)return null; if(row.fingerprint!==fingerprint)throw new OperatorOperationError("idempotency_conflict"); return JSON.parse(row.response_json); }
  async create(command: OperatorCreateCommand): Promise<OperatorMutationResult> {
    const previous=await this.replay(command.context,"createOperator",command.key,command.fingerprint); if(previous)return previous;
    const validationRow=await this.database.prepare("SELECT record_json FROM portal_operator_validations WHERE validation_id=? AND actor_id=? AND expires_at>?").bind(command.request.validationId,command.context.memberId,this.now()).first<{record_json:string}>();
    if(!validationRow)throw new OperatorOperationError("operator_validation_required");
    const validation=OperatorValidationSchema.parse(JSON.parse(validationRow.record_json)); const record=await command.buildRecord(validation); const response={operatorId:record.operatorId,etag:record.etag};
    try { await this.database.batch([this.guard(command.context),this.database.prepare("DELETE FROM portal_mutation_guard"),
      this.database.prepare("DELETE FROM portal_operator_validations WHERE validation_id=? AND actor_id=? AND expires_at>?").bind(command.request.validationId,command.context.memberId,this.now()),
      this.database.prepare("INSERT INTO portal_mutation_guard SELECT changes()"),this.database.prepare("DELETE FROM portal_mutation_guard"),
      this.database.prepare("INSERT INTO portal_idempotency_receipts VALUES (?,'createOperator',?,?,?,?)").bind(command.context.memberId,command.key,command.fingerprint,JSON.stringify(response),command.occurredAt),
      this.database.prepare("INSERT INTO portal_operators(operator_id,document_type,base_url,declared_operator_id,record_json,created_at) VALUES(?,?,?,?,?,?)").bind(record.operatorId,record.documentType,record.baseUrl,record.descriptor.declaredOperatorId,JSON.stringify(record),Math.floor(Date.parse(command.occurredAt)/1000)),
      this.database.prepare("INSERT INTO portal_admin_audit(audit_event_id,actor_id,action,resource_type,resource_id,occurred_at,request_id,document_type,reason,details_json) VALUES(?,?,'operator.created','operator',?,?,?,?,NULL,?)").bind(command.auditEventId,command.context.memberId,record.operatorId,Math.floor(Date.parse(command.occurredAt)/1000),command.requestId,record.documentType,JSON.stringify({validationId:command.request.validationId,declaredOperatorId:record.descriptor.declaredOperatorId,baseUrl:record.baseUrl}))]); return response;
    } catch(error) { const replayed=await this.replay(command.context,"createOperator",command.key,command.fingerprint); if(replayed)return replayed; const current=await this.database.prepare("SELECT 1 FROM portal_operator_validations WHERE validation_id=? AND actor_id=? AND expires_at>?").bind(command.request.validationId,command.context.memberId,this.now()).first(); if(!current)throw new OperatorOperationError("operator_validation_required"); throw error; }
  }
  async updateMetadata(command: OperatorMetadataCommand): Promise<OperatorMutationResult> { const previous=await this.replay(command.context,"updateOperatorMetadata",command.key,command.fingerprint); if(previous)return previous; const row=await this.database.prepare("SELECT operator_id,record_json,revision,created_at FROM portal_operators WHERE operator_id=?").bind(command.operatorId).first<OperatorRow>(); if(!row)throw new OperatorOperationError("not_found"); const current=OperatorRecordSchema.parse(JSON.parse(row.record_json)); if(current.etag!==command.expectedEtag)throw new OperatorOperationError("precondition_failed"); const record=await command.buildRecord(current); const response={operatorId:record.operatorId,etag:record.etag}; try { await this.database.batch([this.guard(command.context),this.database.prepare("DELETE FROM portal_mutation_guard"),this.database.prepare("INSERT INTO portal_idempotency_receipts VALUES (?,'updateOperatorMetadata',?,?,?,?)").bind(command.context.memberId,command.key,command.fingerprint,JSON.stringify(response),command.occurredAt),this.database.prepare("UPDATE portal_operators SET record_json=?,revision=revision+1 WHERE operator_id=? AND revision=? AND json_extract(record_json,'$.etag')=?").bind(JSON.stringify(record),command.operatorId,row.revision,command.expectedEtag),this.database.prepare("INSERT INTO portal_mutation_guard SELECT changes()"),this.database.prepare("DELETE FROM portal_mutation_guard"),this.database.prepare("INSERT INTO portal_admin_audit(audit_event_id,actor_id,action,resource_type,resource_id,occurred_at,request_id,document_type,reason,details_json) VALUES(?,?,'operator.metadata_changed','operator',?,?,?,?,NULL,?)").bind(command.auditEventId,command.context.memberId,command.operatorId,Math.floor(Date.parse(command.occurredAt)/1000),command.requestId,current.documentType,JSON.stringify({before:{name:current.name,description:current.description},after:command.request}))]); return response; } catch(error){const replayed=await this.replay(command.context,"updateOperatorMetadata",command.key,command.fingerprint);if(replayed)return replayed;const latest=await this.get(command.context,command.operatorId);if(!latest)throw new OperatorOperationError("not_found");if(latest.etag!==command.expectedEtag)throw new OperatorOperationError("precondition_failed");throw error;} }
  async get(context: AdminContext,id:string){await this.authorize(context);const row=await this.database.prepare("SELECT record_json FROM portal_operators WHERE operator_id=?").bind(id).first<{record_json:string}>();return row?OperatorRecordSchema.parse(JSON.parse(row.record_json)):null;}
  async list(context:AdminContext,query:ListBundlesQuery):Promise<ListOperatorsResponse>{await this.authorize(context);if(!await this.database.prepare("SELECT 1 FROM portal_document_types WHERE document_type=?").bind(query.documentType).first())throw new OperatorOperationError("not_found");const limit=query.limit??25;const scope=await schemaHash({documentType:query.documentType});let beforeTime=Number.MAX_SAFE_INTEGER,beforeId="\uffff";if(query.cursor){try{const cursor=JSON.parse(atob(query.cursor.replaceAll("-","+").replaceAll("_","/")));if(cursor.scope!==scope||!Number.isSafeInteger(cursor.beforeTime)||typeof cursor.beforeId!=="string")throw new Error();beforeTime=cursor.beforeTime;beforeId=cursor.beforeId;}catch{throw new OperatorOperationError("invalid_request");}}const result=await this.database.prepare("SELECT operator_id,record_json,revision,created_at FROM portal_operators WHERE document_type=? AND (created_at<? OR (created_at=? AND operator_id<?)) ORDER BY created_at DESC,operator_id DESC LIMIT ?").bind(query.documentType,beforeTime,beforeTime,beforeId,limit+1).all<OperatorRow>();const page=result.results.slice(0,limit);const items=page.map(row=>{const record=OperatorRecordSchema.parse(JSON.parse(row.record_json));const{descriptor,...summary}=record;return OperatorListItemSchema.parse({...summary,supportedDocumentContractIdxs:descriptor.supportedDocumentContracts[record.documentType]});});const last=page.at(-1);return{items,nextCursor:result.results.length>limit&&last?btoa(JSON.stringify({scope,beforeTime:last.created_at,beforeId:last.operator_id})).replaceAll("+","-").replaceAll("/","_").replace(/=+$/,""):null};}
}
