/**
 * Public entrypoint for UniDocs tenant data-plane contracts.
 */
export {
  DocumentContentFormatVersion,
  DocumentTypePattern,
  documentLocationContentType,
  documentSnapshotContentType,
} from "@unidocs/protocol";
export type { DocumentLocationContentType, DocumentSnapshotContentType } from "@unidocs/protocol";
export {
  TenantApiErrorMap,
  TenantApiV1BasePath,
  tenantApiContract,
} from "./contract.js";
export type { TenantApiContract } from "./contract.js";
export {
  AddressedPingSchema,
  AppendPingRequestSchema,
  CasBlobRefSchema,
  CasCapabilityGrantSchema,
  CreateDocumentRequestSchema,
  CreateThreadRequestSchema,
  CursorSchema,
  DocumentAuditActionSchema,
  DocumentAuditActions,
  DocumentAuditEventSchema,
  DocumentContractIdxSchema,
  DocumentContractRecordSchema,
  DocumentLocationSchema,
  DocumentRecordSchema,
  DocumentTypeSchema,
  IdempotentMutationHeadersSchema,
  IsoDateTimeSchema,
  ListDocumentAuditEventsResponseSchema,
  ListDocumentsQuerySchema,
  ListDocumentsResponseSchema,
  ListPublicDocumentTypesResponseSchema,
  ListThreadsQuerySchema,
  ListThreadsResponseSchema,
  ListVersionsResponseSchema,
  MessageContentSchema,
  MoveCurrentVersionRequestSchema,
  MutationHeadersSchema,
  PaginationQuerySchema,
  PingIdxSchema,
  PingRecordSchema,
  PongIdxSchema,
  PongRecordSchema,
  PublicDocumentTypeSchema,
  PublicTypeCardIconPngSchema,
  PublicTypeCardIconSchema,
  PublicTypeCardIconSvgSchema,
  PublicTypeCardLocaleSchema,
  PublicTypeCardSchema,
  SValueSchemaSchema,
  SnapshotStreamSchema,
  TenantApiErrorSchema,
  ThreadDetailSchema,
  ThreadRefSchema,
  TypeCardIconRasterSizeSchema,
  VersionIdxSchema,
  VersionRecordSchema,
} from "./schemas.js";
export type {
  AddressedPing,
  AppendPingRequest,
  CasBlobRef,
  CasCapabilityGrant,
  CreateDocumentRequest,
  CreateThreadRequest,
  DocumentAuditAction,
  DocumentAuditEvent,
  DocumentContractRecord,
  DocumentLocation,
  DocumentRecord,
  ListDocumentAuditEventsResponse,
  ListDocumentsQuery,
  ListDocumentsResponse,
  ListPublicDocumentTypesResponse,
  ListThreadsQuery,
  ListThreadsResponse,
  ListVersionsResponse,
  MessageContent,
  MoveCurrentVersionRequest,
  PaginationQuery,
  PingRecord,
  PongRecord,
  PublicDocumentType,
  PublicTypeCard,
  PublicTypeCardIcon,
  PublicTypeCardIconPng,
  PublicTypeCardIconSvg,
  PublicTypeCardLocale,
  SValueSchema,
  TenantApiError,
  TenantErrorData,
  ThreadDetail,
  ThreadRef,
  VersionRecord,
} from "./schemas.js";
